[benchmark_profiles.benchmark_profile_1]
include_legacy_baseline = false
workers = [4, 8, 12, 16]

[benchmark_profiles.benchmark_profile_2]
include_legacy_baseline = false
workers = [4, 6, 8]

[benchmark_profiles.benchmark_profile_3]
include_legacy_baseline = true
workers = [4, 8, 12, 16]

[benchmark_profiles.benchmark_profile_4]
include_legacy_baseline = true
workers = [4, 6, 8]

[production_profiles.elt_default_w4]
workflow = "elt"
workers = 4
pipeline = "parquet_duckdb"
parallel_profile = "large_query"
ordered = "unordered"
large_query_mode = true

[production_profiles.elt_server_limited_w8]
workflow = "elt"
workers = 8
pipeline = "parquet_duckdb"
parallel_profile = "large_query"
ordered = "unordered"
large_query_mode = true

[production_profiles.elt_full_w16]
workflow = "elt"
workers = 16
pipeline = "parquet_duckdb"
parallel_profile = "large_query"
ordered = "unordered"
large_query_mode = true

[production_profiles.etl_default_w4]
workflow = "etl"
workers = 4
pipeline = "polars_duckdb"
parallel_profile = "large_query"
ordered = "unordered"
large_query_mode = true

[production_profiles.etl_server_limited_w8]
workflow = "etl"
workers = 8
pipeline = "polars_duckdb"
parallel_profile = "large_query"
ordered = "unordered"
large_query_mode = true

[production_profiles.etl_full_w16]
workflow = "etl"
workers = 16
pipeline = "polars_duckdb"
parallel_profile = "large_query"
ordered = "unordered"
large_query_mode = true

[defaults.mine]
default_workers = 16
large_query_threshold_rows = 50000
workers_above_threshold = 16
workers_when_size_unknown = 16
production_profile_switch_rows = 50000
production_elt_small_profile = "elt_full_w16"
production_elt_large_profile = "elt_full_w16"
production_etl_small_profile = "etl_full_w16"
production_etl_large_profile = "etl_full_w16"
benchmark_small_profile = "benchmark_profile_3"
benchmark_switch_threshold_rows = 50000
benchmark_large_profile = "benchmark_profile_1"

[mines.legumemine]
display_name = "LegumeMine"
host_patterns = ["mines.legumeinfo.org"]
path_prefixes = ["/legumemine"]
default_workers = 4
workers_above_threshold = 4
workers_when_size_unknown = 4
production_elt_small_profile = "elt_default_w4"
production_elt_large_profile = "elt_default_w4"
production_etl_small_profile = "etl_default_w4"
production_etl_large_profile = "etl_default_w4"
benchmark_small_workers = []
benchmark_small_profile = "benchmark_profile_4"
benchmark_large_profile = "benchmark_profile_2"

[mines.maizemine]
display_name = "MaizeMine"
host_patterns = ["maizemine.rnet.missouri.edu"]
path_prefixes = ["/maizemine"]
default_workers = 8
workers_above_threshold = 8
workers_when_size_unknown = 8
production_elt_small_profile = "elt_server_limited_w8"
production_elt_large_profile = "elt_server_limited_w8"
production_etl_small_profile = "etl_server_limited_w8"
production_etl_large_profile = "etl_server_limited_w8"
benchmark_small_profile = "benchmark_profile_4"
benchmark_large_profile = "benchmark_profile_2"

[mines.thalemine]
display_name = "ThaleMine"
host_patterns = ["bar.utoronto.ca"]
path_prefixes = ["/thalemine"]
benchmark_small_profile = "benchmark_profile_3"
benchmark_large_profile = "benchmark_profile_1"

[mines.oakmine]
display_name = "OakMine"
host_patterns = ["urgi.versailles.inra.fr", "urgi.versailles.inrae.fr"]
path_prefixes = ["/OakMine_PM1N"]
benchmark_small_profile = "benchmark_profile_3"
benchmark_large_profile = "benchmark_profile_1"

[mines.wheatmine]
display_name = "WheatMine"
host_patterns = ["urgi.versailles.inra.fr", "urgi.versailles.inrae.fr"]
path_prefixes = ["/WheatMine"]
benchmark_small_profile = "benchmark_profile_3"
benchmark_large_profile = "benchmark_profile_1"
