[benchmark_profiles.benchmark_profile_1]
include_legacy_baseline = true
workers = [2, 4, 6, 8, 10, 12, 14, 16, 18]

[benchmark_profiles.benchmark_profile_2]
include_legacy_baseline = false
workers = [4, 8, 12, 16]

[benchmark_profiles.benchmark_profile_3]
include_legacy_baseline = false
workers = [4, 6, 8]

[benchmark_profiles.benchmark_profile_4]
include_legacy_baseline = true
workers = [4, 6, 8]

[defaults.mine]
default_workers = 16
large_query_threshold_rows = 50000
workers_above_threshold = 12
benchmark_small_profile = "benchmark_profile_1"
benchmark_switch_threshold_rows = 50000
benchmark_large_profile = "benchmark_profile_2"

[mines.legumemine]
display_name = "LegumeMine"
host_patterns = ["mines.legumeinfo.org"]
path_prefixes = ["/legumemine"]
default_workers = 4
workers_above_threshold = 4
benchmark_small_workers = []
benchmark_small_profile = "benchmark_profile_4"
benchmark_large_profile = "benchmark_profile_3"

[mines.maizemine]
display_name = "MaizeMine"
host_patterns = ["maizemine.rnet.missouri.edu"]
path_prefixes = ["/maizemine"]

[mines.thalemine]
display_name = "ThaleMine"
host_patterns = ["bar.utoronto.ca"]
path_prefixes = ["/thalemine"]

[mines.oakmine]
display_name = "OakMine"
host_patterns = ["urgi.versailles.inra.fr", "urgi.versailles.inrae.fr"]
path_prefixes = ["/OakMine_PM1N"]

[mines.wheatmine]
display_name = "WheatMine"
host_patterns = ["urgi.versailles.inra.fr", "urgi.versailles.inrae.fr"]
path_prefixes = ["/WheatMine"]
