SMALL_MATRIX_ROWS = "5000,10000,25000"
LARGE_MATRIX_ROWS = "50000,100000,250000"
BATCH_SIZE_TEST_ROWS = 10000
BATCH_SIZE_TEST_CHUNK_ROWS = "1000,2500,5000,7500,10000"
WARMUP_ROWS = 2000
PROGRESS_LOG_INTERVAL_ROWS = 100000
RETRY_BACKOFF_INITIAL_SECONDS = 2.0
RETRY_BACKOFF_MAX_SECONDS = 12.0
